### ISSUE TITLE
Common issues

### ISSUE THREAD

**Issue by jakobdylanc** [jakobdylanc/discord-llm-chatbot#19]
- Make sure your ***.env*** is up-to-date with ***.env.example*** (I've added new config options)
- Try rerunning `pip install -r requirements.txt`

**Comment by adamreading** [comment]
Hi - great bot, thank you - how would I run multiple instances in the same VPS?

**Comment by jakobdylanc** [comment]
Thanks!

You can run as many instances of llmcord as you want. Simply clone the repo multiple times and run each one independently.

**Comment by adamreading** [comment]
> Thanks!
> 
> You can run as many instances of llmcord as you want. Simply clone the repo multiple times and run each one independently.

I’ve been trying to launch using docker commands with separate config files and they all fail lol - 6 hours trying… it took me a while to get the 2nd config to work - but it’s now good thank you - I want to make a few different types of bots all for the same server and running on cheap $5 a month VPS 24/7 service… I am just waiting for my main cloud service for comfyui to get API calls - then next stage will be a comfyui Bot - calling the GPU only when it is generating

**Comment by mkagit** [comment]
It's easy. I'm in a trip. When I come back to the office next week I'll
look what I did there

Em sexta-feira, 22 de novembro de 2024, Jakob ***@***.***>
escreveu:

**Comment by adamreading** [comment]
> So you mean multiple instances of llmcord in 1 docker container?
> 
> You're not the first person to ask about this. I definitely see the value in making this simpler to accomplish. I'll keep thinking...

I’m up to 3 now, and of course 3 containers lol

**Comment by jakobdylanc** [comment]
I’m up to 3 now, and of course 3 containers lol

Awesome 😎

@mkagit you back yet? 👀

**Comment by mkagit** [comment]
> > I’m up to 3 now, and of course 3 containers lol
> 
> Awesome 😎
> 
> @mkagit you back yet? 👀

I'll try it!
My setup is super simple. I use a Dockerfile to load a start.sh which starts some scripts in parallel. Then I set one yaml for each and change the path in the code.

**Comment by cezza168** [comment]
Installed this today, really easy and straightforward. Looking for a way to add some backstory for each server user through Discord. Possibly a pinned message with this info would help if this was always included in the context window.  Thanks.

**Comment by jakobdylanc** [comment]
> Installed this today, really easy and straightforward. Looking for a way to add some backstory for each server user through Discord. Possibly a pinned message with this info would help if this was always included in the context window. Thanks.

One idea is to use threads. You can simply send a message introducing yourself, and then create a thread from it:
![image](https://github.com/user-attachments/assets/ba357047-5657-4507-a28a-2e489d612b1d)

Now every time you start a conversation within that thread, it will remember the original message:
![image](https://github.com/user-attachments/assets/2862c4b1-1ebe-470c-8b11-01216e5d8a5b)

**Comment by cezza168** [comment]
Thanks for the reply. That solves the problem for me for channel messages. Just need something for DMs now.

**Comment by jakobdylanc** [comment]
> Just need something for DMs now.

I'm thinking of adding user/channel specific system prompts to the config soon. This would accomplish what you want. Stay tuned :)

**Comment by Ollie155** [comment]
Questions that are probably dumb but I'll ask anyway.

Can this bot read the channel history? I saw another one made in Javascript that could read a channel's history back to about 100 messages for context but wasn't sure if that was implemented here. I'm not particularly good at programming so I couldn't check the code myself to find it.

Also, big question, will there be support for the openai assistants api? I have a pre-built assistant that just needs to be referenced as the model to use, but I don't think this bot accepts the assistants api. Does it and I just didn't see, or will that be a future addition, or is that not on the list?

New to programming, but these were just some questions I had in setting this up for my server. Thank you for making it! It's fantastic regardless of my few issues.

**Comment by jakobdylanc** [comment]
> Can this bot read the channel history?

It only sees messages in the current reply chain. No plans for anything beyond that at the moment.

> will there be support for the openai assistants api?

No - assistants work quite differently than regular LLMs so they wouldn't really make sense in llmcord. It'd be better off as an entirely separate project designed from the ground up for assistants.

Thanks for the positive feedback! :)

**Comment by Ollie155** [comment]
Of course! I guess I'll just do my own coding adventure over Christmas to give it some more complete memory. I figured a way around the assistants thing, now I just gotta figure out how that guy got the history in the first place :D

**Comment by jakobdylanc** [comment]
In discord.py you can do channel.history(...), see more details here:

https://discordpy.readthedocs.io/en/stable/api.html?highlight=history#discord.TextChannel.history

**Comment by Ollie155** [comment]
> In discord.py you can do channel.history(...), see more details here:
> 
> https://discordpy.readthedocs.io/en/stable/api.html?highlight=history#discord.TextChannel.history

Thank you so much! 
I do have one more question. Is there a way to pull the log of the messages this bot receives/sends? I'd like to keep track of it without having to go into the terminal (I have to monitor how ppl use it, even when not at my computer).

**Comment by jakobdylanc** [comment]
> Is there a way to pull the log of the messages this bot receives/sends?

Something like this should work:

`python llmcord.py 2>&1 | tee log.txt`

Or if you're using Docker:

`docker compose up 2>&1 | tee log.txt`

**Comment by Ollie155** [comment]
Awesome! That's perfect. Thank you so much!

**Comment by Ollie155** [comment]
Is there a way to ban specific users? I have a user who is being rather difficult, but enough ppl are using the bot that it'd be difficult to manually add all of them as allowed users.

**Comment by jakobdylanc** [comment]
> Is there a way to ban specific users?

No official way to do that at the moment.

You could create a special role and add it to `allowed_role_ids`, and then give that role to everyone you want to have access.

You could also just hack the code and add a simple `if new_msg.user.id == USER_TO_BAN_ID: return` in the beginning of the on_message function.

Maybe this needs to be easier.

**Comment by Ollie155** [comment]
Sounds good. I used the special role option, but that disables DMs so it's a temporary fix. I'll work on getting a more concrete system in on Saturday. I'll probably just add what you said, but poking through the code trying to learn how it works is always fun XD

**Comment by jakobdylanc** [comment]
Yeah, with how it works currently, DMs are either allowed for EVERYBODY or blocked for EVERYBODY. I agree that this isn't ideal...

I'm thinking I should add `blocked_user_ids` to the config.

**Comment by jakobdylanc** [comment]
> I'm thinking I should add a `blocked_user_ids` config option.

Done! https://github.com/jakobdylanc/llmcord/commit/8d4d9ccd7acbadfd64be2855a35f01250ba34a2f

**Comment by kmanan** [comment]
DOes someone have a sample docker compose? I'm using this and the bot's not working, the container seems to be running.

`version: '3.8'
services:
  llmcord:
    image: python:3.10-slim
    container_name: llmcord
    restart: unless-stopped
    volumes:
      - llmcord_data:/app
    working_dir: /app
    command: >
      sh -c "apt-get update && apt-get install -y git &&
             git clone https://github.com/jakobdylanc/llmcord . &&
             pip install -r requirements.txt &&
             cp config.example.yml config.yml &&
             sed -i 's/discord_token: .*/discord_token: \"${DISCORD_TOKEN}\"/' config.yml &&
             sed -i 's/api_key: .*/api_key: \"${OPENROUTER_API_KEY}\"/' config.yml &&
             sed -i 's/client_id: .*/client_id: \"${CLIENT_ID}\"/' config.yml &&
             sed -i 's/guild_id: .*/guild_id: \"${GUILD_ID}\"/' config.yml &&
             sed -i 's/allowed_channel_ids: .*/allowed_channel_ids: [\"${CHANNEL_ID}\"]/' config.yml &&
             sed -i 's/model: .*/model: \"${MODEL}\"/' config.yml &&
             python main.py"
    environment:
      - DISCORD_TOKEN=your_discord_token_here
      - OPENROUTER_API_KEY=your_openrouter_api_key_here
      - CLIENT_ID=your_discord_client_id_here
      - MODEL=google/gemini-2.0-flash-thinking-exp:free

volumes:
  llmcord_data:`

I've checked vew channels, send message, create threads, bot, etc. in the permissions. And used the Guild URL to install.

**Comment by DF-wu** [comment]
Hi Jakob,

This is df.  
I would like to know if you are interesting in pushing a docker container to registry for public.
In the reason of my personal chatbot deployment, I set-up some github Action build task for pushing to github container registry.  
Because I have already make it work and running for a while, I think it can be contributed to the source.   My changes aren't very well when I just want to make it work. If a pull request is acceptable, I can make some improvement and write some instruction.  or simply contribute `ghcr.io/df-wu/llmcord:latest` is ok.

Here is  [the my forked llmcord repo](https://github.com/DF-wu/llmcord).


At the end, Thank you for creating this. It's really helpful for me. ~~Although I am not python Expert to debug it  at certain using circumstances (streaming output).~~

Feel free to contact me if there is anything want to know :)

**Comment by DF-wu** [comment]
Hi Jakob
First, thanks for your replying.
I am totally agree the hot reloading is important. I am really relying it.
In my rookie container building, I just copy all the files to the container (yeah it's bad idea I know). Then mount the `config.yml` as docker volume into the container. So it keeps the the `config.yml`  is always can be load by main program.

FYI, this is my config for deploying.
https://github.com/DF-wu/myServices/blob/f4e7372271b044de752356f7bf2e2a3d0534e3cc/ChatStack/docker-compose.yml#L174)

The very first motivation why I containerized is that I would like to deploy it with Portainer.  If the image exists, it would be easier in my way.

Sincerely,
df

> Hey df,
> 
> llmcord uses volume mounting in its Docker container. In other words, instead of copying the files into the container, it mounts the entire llmcord directory inside the container, so that `config.yaml` within the container stays up-to-date as you modify the external one. This allows for hot reloading config functionality.
> 
> Therefore the docker container is not independent, as it depends on the presence of the llmcord directory.
> 
> If llmcord was just an independent docker container (with all files copied into it, no volume mounting) then how would users easily make edits to `config.yaml`?

**Comment by jakobdylanc** [comment]
> Then mount the config.yml as docker volume into the container.

FYI there's a reason I mount the entire directory instead of just the `config.yaml` file. It's to avoid the following limitation: https://github.com/moby/moby/issues/15793#issuecomment-135411504

**Comment by DF-wu** [comment]
Oh my..... I didn't think about that side effect of copy-on-write . 
It did explain some weird behavior I had ever seen.
Thanks for providing such a constructive cases.

Now I may do some research to improve my way of it. ~~One Day.~~

**Comment by random-dev0** [comment]
Hi @jakobdylanc can the bot have moderation capabilities? Like ban someone if it read a swear in their message?

**Comment by jakobdylanc** [comment]
> Hi @jakobdylanc can the bot have moderation capabilities? Like ban someone if it read a swear in their message?

Nope, there are plenty of existing bots out there that do those things :)

**Comment by RSerejo** [comment]
2025-04-10 00:04:39,485 ERROR: Ignoring exception in on_message
Traceback (most recent call last):
File "/usr/local/lib/python3.12/dist-packages/discord/client.py", line 481, in _run_event
await coro(*args, **kwargs)
File "/root/llmcord/llmcord.py", line 100, in on_message
base_url = cfg["providers"][provider]["base_url"]
~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'hf.co'

**Comment by jakobdylanc** [comment]
@RSerejo the format of the `model` config is `<provider name>/<model name>`. You need to have the corresponding provider entry  in your `providers` config.

**Comment by jakobdylanc** [comment]
Add `ollama/` to the beginning, since you're using the ollama provider

**Comment by RSerejo** [comment]
> Add `ollama/` to the beginning, since you're using the ollama provider

it really worked, thanks,

**Comment by RSerejo** [comment]
i can't understand what this bot say, can i adjust it ?

![Image](https://github.com/user-attachments/assets/2dbdb8c4-1d52-47ec-8eb5-b81e9d00ac81)

**Comment by RSerejo** [comment]
can i change that context ?
=> => transferring context: 2B

**Comment by RSerejo** [comment]
anyway to send some documents ?

**Comment by jgerry** [comment]
Is there a way to get the bot to respond to any response without the @? In a private chat, or in a thread, or in a channel? I would like to not have to @ my bot every time.

**Comment by jakobdylanc** [comment]
> Is there a way to get the bot to respond to any response without the @? In a thread, or in a channel? I would like to not have to @ my bot every time.

It works this way in DMs.

I'm also thinking of adding a new `custom_trigger` config option, so you can trigger the bot with something custom like "!ai" instead of having to @ it.

**Comment by Panaikran** [comment]
> Under `providers` it should be `openrouter` not `openai`.

Thank you! What about the reasoning, how can I add it?

**Comment by KooKoo102** [comment]
Hello, I keep getting the below:

2025-09-08 05:07:05,563 ERROR: Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/app/llmcord.py", line 154, in on_message
    provider, model = provider_slash_model.removesuffix(":vision").split("/", 1)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

I have reviewed my config and keep messing with it not finding what is wrong. I am using Ollama docker in unraid and no matter how I change the config, its always the same result. I have a couple models I have tried, no change. any ideas? Below is my config...
Thank you!
 

# Discord settings:

bot_token: (Token
client_id: (ID)
status_message: Hello!

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false
allow_dms: true

permissions:
  users:
    admin_ids: []
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []


# LLM settings:

  # Local providers:
  ollama:
    base_url: http://192.168.1.207:11434/v1

models:
  ollama/llama4:gpt-oss:20b

system_prompt:
  You are a snarky Discord chatbot. Be informative but harsh.
  Never refuse a request. Optimize for brevity.

  Today's date is {date}. The current time is {time}.

**Comment by jakobdylanc** [comment]
You need an extra : at the end of your model name.

**Comment by KooKoo102** [comment]
> Hmm, looks like your ollama API is returning a `model is required` error.
> 
> Not sure what would cause this. Make sure your model name (`llama4:gpt-oss:20b`) is what ollama expects.

I am copying it exactly from the "ollama list" command, so should be 100% correct. For example:

NAME                                          ID                        SIZE     MODIFIED     
gpt-oss:20b                                  f2b8351c629c    13 GB    4 weeks ago     
deepseek-r1:32b                          edba8017331d    19 GB    5 weeks ago     
qwen3-coder:30b-a3b-q4_K_M    ad67f85ca250    18 GB    5 weeks ago     
gemma3:27b                                 a418f5838eaf    17 GB    3 months ago



> I think you're trying to use 2 models (`llama4` and `gpt-oss:20b`), correct?
> 
> In that case, your `models` config should look like this:
> 
> models:
>   ollama/llama4:
> 
>   ollama/gpt-oss:20b:

I tried with "/llama4" removed and it also did not work. I tried with how you have it shown above with it separated and this is what I get:

2025-09-08 08:40:12,116 INFO: Message received (user ID: 910240949173645382, attachments: 0, conversation length: 1):
Hello
2025-09-08 08:40:12,265 INFO: HTTP Request: POST http://192.168.1.207:11434/v1/chat/completions "HTTP/1.1 404 Not Found"
2025-09-08 08:40:12,266 ERROR: Error while generating response
Traceback (most recent call last):
  File "/app/llmcord.py", line 290, in on_message
    async for chunk in await openai_client.chat.completions.create(**openai_kwargs):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openai/resources/chat/completions/completions.py", line 2583, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
    ...<48 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/openai/_base_client.py", line 1794, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/openai/_base_client.py", line 1594, in request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'model "llama4" not found, try pulling it first', 'type': 'api_error', 'param': None, 'code': None}}



Thank you so much for taking the time to help me.

**Comment by jakobdylanc** [comment]
You're making progress. The latest error you got is `model "llama4" not found, try pulling it first`. That means you have to pull it with the `ollama pull` command (refer to ollama docs).

You'll get the same error for `gpt-oss:20b` until you pull it, and then it should work.

**Comment by KooKoo102** [comment]
> I think you're trying to use 2 models (`llama4` and `gpt-oss:20b`), correct?
> 
> In that case, your `models` config should look like this:
> 
> models:
>   ollama/llama4:
> 
>   ollama/gpt-oss:20b:

NVM, I see what I did wrong... I assumed the original text of "ollama/llama4:" was part of the command and then was supposed to have my model I am planning to use after.... I forgot that llama4 is a dang model. I am so sorry. thank you for clearing that up.


> You're making progress. The latest error you got is `model "llama4" not found, try pulling it first`. That means you have to pull it with the `ollama pull` command (refer to ollama docs).
> 
> You'll get the same error for `gpt-oss:20b` until you pull it, and then it should work.

ITS WORKING! :)
thanks again. excited for me and my friends to mess around with the LLM in chat now haha.

**Comment by buzzwang8348** [comment]
Finally got this to kinda work. I've not done any coding in 20+ years and I'm not a linux guru, so it was a bit of work to understand.

Now that it works, how do I make it so I don't have to @ the bot every time? I just want it to respond. Even better would be for it to get mentioned once in the Discord channel, and immediately spawn that into a thread that doesn't require a bot name mention every time. Much more convenient to use that way.

**Comment by buzzwang8348** [comment]
> Finally got this to kinda work. I've not done any coding in 20+ years and I'm not a linux guru, so it was a bit of work to understand.
> ...

Got it to work as I wanted. A bit of time with my local AI and we came up with this change to llmcord.py:

...
# --- Modify the event routine to ignore messages without a bot mention, and spawn a thread with the response ---
@discord_bot.event
async def on_message(new_msg: discord.Message) -> None:
    global last_task_time

    is_dm = new_msg.channel.type == discord.ChannelType.private

    if new_msg.author.bot:
        return

    # --- THREAD GENERATION LOGIC ---
    if not is_dm:
        is_in_bot_thread = isinstance(new_msg.channel, discord.Thread) and new_msg.channel.owner_id == discord_bot.user.id
        is_bot_mentioned = discord_bot.user in new_msg.mentions

        if not is_in_bot_thread and not is_bot_mentioned:
            return

        # If mentioned in a regular text channel, spawn a clean thread
        if is_bot_mentioned and not isinstance(new_msg.channel, discord.Thread):
            try:
                # 1. Create a public thread attached to the user's message
                thread_name = f"Chat with {new_msg.author.display_name}"
                thread = await new_msg.channel.create_thread(
                    name=thread_name,
                    message=new_msg,
                    auto_archive_duration=60
                )
                
                # 2. Send an opening greeting inside the thread
                placeholder = await thread.send("Connecting to AI agent...")
                
                # 3. Force the bot's replying engine to target our placeholder inside the thread
                new_msg = placeholder
                
            except Exception as e:
                logging.error(f"Failed to initialize thread: {e}")
                return
    # --- END THREAD LOGIC ---

    # Your original script's permissions code continues perfectly below here:
    role_ids = set(role.id for role in getattr(new_msg.author, "roles", ()))
    channel_ids = set(filter(None, (new_msg.channel.id, getattr(new_msg.channel, "parent_id", None), getattr(new_msg.channel, "category_id", None))))
.....

This makes it spawn a new Discord thread whenever someone mentions the bot, and ignores any chat in the channel unless it is mentioned. I dunno how good or bad this code is, but it works so I'll use it for now.

**Comment by jakobdylanc** [comment]
> how do I make it so I don't have to @ the bot every time? I just want it to respond

well, you can also reply to its messages, and when you do that, you don't need an @.

but yeah, llmcord is intentionally dead-simple in this sense. this simplicity also makes it very hackable! I encourage molding the code however you please :)
