### ISSUE TITLE
Fresh Install - Trying to use ooba api 

### ISSUE THREAD

**Issue by IntrovertedFL** [jakobdylanc/discord-llm-chatbot#20]
I did a fresh install and have the ooba api running, but can not run as anything I try different in the .env I keep getting this error

```
Traceback (most recent call last):
  File "/home/aaron/Documents/GitHub/llmcord/llmcord.py", line 18, in <module>
    LOCAL_LLM: bool = env["LLM"].startswith("local/")
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'LLM'
```
Any suggestions on things I can try? I've installed all requirements. 

My env 

```
LLM = local/openai/model
CUSTOM_SYSTEM_PROMPT = You are a snarky Discord chatbot.
CUSTOM_DISCORD_STATUS = 

ALLOWED_CHANNEL_IDS = 
ALLOWED_ROLE_IDS = 
MAX_IMAGES = 5
MAX_MESSAGES = 20

LOCAL_SERVER_URL = http://localhost:5000/v1
LOCAL_API_KEY = 
OOBABOOGA_CHARACTER = 

# LiteLLM settings:
OPENAI_API_KEY = 
MISTRAL_API_KEY = 
# Add more as needed for other providers
```
Not sure what I am missing here, I used it for weeks up to this point without any issue.

**Comment by jakobdylanc** [comment]
What's your OS? If Windows, make sure your ".env" isn't actually named ".env.txt" (Windows hides file extensions by default).

Let me know if that helps.

**Comment by IntrovertedFL** [comment]
Thanks for responding @jakobdylanc I'm using Pop! OS 22.04 LTS. Any suggestions?

**Comment by IntrovertedFL** [comment]
I apologize for a waste of time here, it was the fork I had, I updated it today, but something must have happened, I wiped it and cloned the repo again and everything is up and running. Thank you so much for your work on this project, it helps to make a Friday night a little more fun for my discord room :)

**Comment by jakobdylanc** [comment]
Awesome to hear 😁 & thank you! I originally wrote this bot for me and my friends to use and it's been super fun for us. I'm glad I can spread the fun to others 👍
