### ISSUE TITLE
Issues when using Oobabooga

### ISSUE THREAD

**Issue by Casuallynoted** [jakobdylanc/discord-llm-chatbot#27]
Trying to use this with Oobabooga atm, but getting this error:

2024-03-31 23:36:25.227 ERROR: Error while streaming response
Traceback (most recent call last):
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 254, in __aiter__
    async for part in self._httpcore_stream:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
    raise exc
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_async/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/llmcord.py", line 176, in on_message
    async for chunk in await acompletion(**kwargs):
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/litellm/utils.py", line 9864, in __anext__
    raise e
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/litellm/utils.py", line 9748, in __anext__
    async for chunk in self.completion_stream:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/openai/_streaming.py", line 150, in __aiter__
    async for item in self._iterator:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/openai/_streaming.py", line 167, in __stream__
    async for sse in iterator:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/openai/_streaming.py", line 158, in _iter_events
    async for sse in self._decoder.aiter(self.response.aiter_lines()):
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/openai/_streaming.py", line 295, in aiter
    async for line in iterator:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_models.py", line 963, in aiter_lines
    async for text in self.aiter_text():
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_models.py", line 950, in aiter_text
    async for byte_content in self.aiter_bytes():
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_models.py", line 929, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_models.py", line 987, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_client.py", line 149, in __aiter__
    async for chunk in self._stream:
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 253, in __aiter__
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/mnt/XDDA/Downloads/discord-llm-chatbot/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The model I'm using is a GPTQ llama2 model running via Exllama.

**Comment by jakobdylanc** [comment]
What model are you using? Can you try others?

Also try updating litellm via "pip install -U litellm".
